### PR TITLE
Add test cases for property paths that include a dot or space character (not the empty string)

### LINKED ISSUE #6: Writing to the "." key in an object throws an Automerge error "RangeError: key must not be an empty string"
I am writing some property-based tests for a project using the [fast-check](https://github.com/dubzzz/fast-check) library. It likes to generate random objects like: 

```ts
{"!":{"!":{"!":{".": false}}}}
```

A counterexample that the testing library found used an object such as the one above, which at some point generated the error `RangeError: key must not be an empty string` from somewhere in the Automerge wasm. I was able to narrow things down, and it seems to be introduced by automerge-patcher.

Using automerge-patcher, code that makes Automerge throw the error:

```ts
const data = Automerge.from({".": 0});
const toApply: Automerge.Patch = {
    action: "put",
    path: ["."],
    value: 1
}
Automerge.change(data, (d) => {
    AutomergePatcher.patch(d, toApply);
});
```

The same code (without automerge-patcher) is accepted by Automerge: 

```ts
const data = Automerge.from({".": 0});
Automerge.change(data, (d) => {
    d["."] = 1
});
```

### PR DESCRIPTION
**Pull request by svdvonde**
Relates to issue #6

### CODE REVIEW

**Comment by acurrieclark** [comment]
Thanks so much for the failing test. I have pushed a fix on this PR which I am happy with, but would value you checking that it fixes your other tests.

Let me know if this fits your needs and I will get it merged and released.

**Comment by svdvonde** [comment]
I'm getting some strange behaviour where a testcase crashes due to some Rust OOM error. I'll need to investigate the root cause. Could be bugs in my own code, could be something else.

**Comment by acurrieclark** [comment]
I have essentially ported the 3rd party code I was using before and removed the `dot-path` element. It was essentially using arrays under the hood anyway. That said, you might have unearthed something new!

Let me know if I can help at all.

**Comment by acurrieclark** [comment]
Should have checked, is that a test which was passing before this change?

**Comment by svdvonde** [comment]
Not really, the property-based testing was supposed to discover issues in my code (edge cases, etc.). Concurrently to the dot-path issue it did raise another issue where some output in some cases was not as expected, so in that sense "the tests work" (but my code does not). The unusual thing is that I don't know why there would be an OOM error. My code does not do heavy computations or potentially infinite loops, so I'm wondering where is the issue? My code, automerge-patcher, or automerge?

Currently I am recreating a subset of the property-based tests in this package to check whether a similar issue pops up. I'm essentially generating random objects, and then I try to write a value to random paths using automerge-patcher. As long as the objects and patches are valid, it should really work and not result in an OOM error.

**Comment by svdvonde** [comment]
I still don't know what the cause is, but I'm seeing similar behaviour when performing a similar test just for `automerge-patcher`. What I'm seeing is very long run-times when I run `npm run test`, where it hangs on the test case that I added, followed by an error (eventually). In this particular case it is the error below, which seems to be related to writing to a key `"\""`, but I have not been able to reproduce it with an ordinary test case.

```
 FAIL  tests/property-based-testing/patch.test.ts > Property-based tests for applying patches > value shoud be writable (with seed=1928611668)
Error: Property failed after 3 tests
{ seed: 1928611668, path: "2:1:0:1:1:1:1:1:1:1:1:1:2:2:2:2:3:3", endOnFailure: true }
Counterexample: [[{"!":"","\"":0},[["!"],["\""]]],0]
Shrunk 17 time(s)
Got TypeError: Cannot create property '"' on string ''
    at Module.setProperty (/Users/sam/VUB/Projects/automerge-patcher/src/helpers.ts:88:19)
    at Module.patch (/Users/sam/VUB/Projects/automerge-patcher/src/patch.ts:96:5)
    at /Users/sam/VUB/Projects/automerge-patcher/tests/property-based-testing/patch.test.ts:16:9
    at _change (file:///Users/sam/VUB/Projects/automerge-patcher/node_modules/@automerge/automerge/dist/mjs/stable.js:356:9)
    at Module.change (file:///Users/sam/VUB/Projects/automerge-patcher/node_modules/@automerge/automerge/dist/mjs/stable.js:227:16)
    at canWrite (/Users/sam/VUB/Projects/automerge-patcher/tests/property-based-testing/patch.test.ts:15:20)
    at /Users/sam/VUB/Projects/automerge-patcher/tests/property-based-testing/patch.test.ts:59:48
    at Array.every (<anonymous>)
    at /Users/sam/VUB/Projects/automerge-patcher/tests/property-based-testing/patch.test.ts:59:22
    at file:///Users/sam/VUB/Projects/automerge-patcher/node_modules/@fast-check/vitest/lib/internals/TestWithPropRunnerBuilder.js:3:41
```

Perhaps it can be worth it to rewrite `getProperty` and `setProperty` using the [`Reflect`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect) api? E.g., via `Reflect.has`, `Reflect.get`, and `Reflect.set`.

**Comment by svdvonde** [comment]
You may not want this in the main project, so I created a branch with the added test case: 

https://github.com/svdvonde/automerge-patcher/tree/property-based-testing

My apologies if the code is messy or has type errors, for some reason my IDE (Jetbrains WebStorm) complains about standard TypeScript things for this project (e.g., "_TS2304: Cannot find name Object_" and "_TS2304: Cannot find name JSON_"), so I wasn't able to properly clean up type errors/warnings. It runs though, so it must be WebStorm being weird.

This is what I added:
`/tests/property-based-testing/patch.test.ts`
This file will check whether a certain property holds. The property in this case is the `canWrite` function. In human language: "given an object, a path, and a value, if we transform the object to an Automerge object, can this value be written to the given path?" Y/N. For the types of objects I'm testing, I believe it should always be yes.

How does the test work?
Essentially the "fast-check" library needs some function that generates random data. To check the property it needs to generate a random object, a random value, and we need to write it to a random (but valid) path in the object.

A function `makeAutomergeCompatibleObject` creates an Automerge compatible object. Essentially a dictionary where the keys are strings and the values are other dictionaries or atomic values (strings, numbers, booleans). Note that this does not even generate objects with arrays. For my use case I don't deal with arrays, so I did not include them here either to not overcomplicate things. 

In the definition of `objectAndPaths` I take a randomly generated object and compute all valid paths in said object. What is returned is now a generator of tuples where the first value is the object, and the second value an array of all possible paths.

The definition of `valueToWrite` is a generator for the kinds of values that will be written to the data, so empty objects, numbers, strings and booleans. For this test I chose these to be innocent values to not overcomplicate things.

Then, `test.prop` will check the property. Given as input the generators `[objectAndPaths, valueToWrite]`, the `fast-check` library will use these to generate a whole bunch of random data and check whether the given property holds. In this case, the property is the given lambda, which checks for every path in the object whether it can be written to. Note that each invocation of `canWrite` creates a new Automerge object and (should) throw it away, so the different writes should not interfere with each other.

```ts
([data, paths]: [object, Path[]], valueToWrite) => {
        return paths.every((path: string[]) => canWrite(data, paths, valueToWrite));
    }
```

`/tests/property-based-testing/helpers/getAllObjectPaths.ts`
Just a quick function to get all paths in the objects that are being generated. Does not work for all objects in general to reduce complexity (e.g., it currently treats arrays as atomic values).

**Comment by acurrieclark** [comment]
Do you know which patch type is being applied in the failure above? It seems that the value at the path given is a string, but a property is being set as if it were an object?

**Comment by acurrieclark** [comment]
Your `canWrite` function seems to be comparing values which will always be equal too, unless I am mistaken?

**Comment by svdvonde** [comment]
Based on the info given in the stacktrace and the way that I programmed the test, it attempts to write to the paths `[["!"],["\""]]` (this is an array of paths that should be writable) of the object `{"!":"","\"":0}`. 

I will try again to write a plain test that shows the unexpected behaviour.

As for the `canWrite` function, indeed I'm assuming that in the circumstances attempted by the testcase, a write should always be possible (otherwise it'll error, or something) and the values should be equal. If they aren't, something strange is foot and the test should fail.

**Comment by acurrieclark** [comment]
I meant [this line here](https://github.com/svdvonde/automerge-patcher/blob/21097e6becfd19cdeee2f806a424c7973bc0f8aa/tests/property-based-testing/patch.test.ts#L21). It will always return true, regardless of the result of the change.

I am not entirely sure how `test.prop` is used, but are you sure that a new document is being created each time? This kind of error would make sense if a property was previously an object, then a test set it to a string, then a later test attempted to set a property on it

**Comment by svdvonde** [comment]
Ah yeah, that line was a quick hack for objects (and is also a typo). It's possible for the test case to write an empty object `{}` to the path, but this empty object is never `===` to the value that is now in the Automerge doc 🤷.

> are you sure that a new document is being created each time?

Well.. Not really. I'm assuming (not unreasonably, I think) that `fast-check` calls the lambda `canWrite` for every piece of data it generates, and that Automerge does not do some weird caching where calling `from` twice on the same object (but different call context) actually returns the 1 Automerge document.

**Comment by svdvonde** [comment]
I'll investigate a bit further, and hopefully I will be able to reduce it to a plain test case.

**Comment by acurrieclark** [comment]
Looks like this should be `path`, not `paths`?

https://github.com/svdvonde/automerge-patcher/blob/a0700a9be03fd9d9eadbde35c6ee6ab88046d22a/tests/property-based-testing/patch.test.ts#L57

**Comment by svdvonde** [comment]
That's unfortunate. A consequence of trying to recreate a test case somewhere else as quickly as possible. 

Test still fails, but let's see where it leads. Hold on.

**Comment by acurrieclark** [comment]
`[[{["__proto__"]:{},"y":true},[["__proto__"],["y"]]],false]` seems to fail, but I am unsure of what all the specific values refer to here.

**Comment by svdvonde** [comment]
My testrun found a failure with a path that contains `valueOf`. Although I might be stupid and make more mistakes where I think something is incorrect, but actually it is correct.

If you think this is also something that should work, then I suppose there might be some weirdness going on still with `getProperty` and `setProperty` in special cases.

**Comment by acurrieclark** [comment]
I imagine this is simply because every object has a [built in](http://devdoc.net/web/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf.html) `valueOf` property. I am not sure if I am worried about supporting that.

**Comment by svdvonde** [comment]
Right, things that (accidentally or not) overwrite internal properties should rightly not be supported. 

I will let this rest for a short while, and revisit it with a clear head. For now, thank you so much for the help.

**Comment by acurrieclark** [comment]
I think the initial patch is very much worthwhile for now. Would you object to me removing the last test and then merging?

**Comment by svdvonde** [comment]
I had already removed the test case locally (and pushed that commit, if that's okay). A merge seems good, since the problem of dot-paths is definitely fixed.

**Comment by acurrieclark** [comment]
Perfect. Thanks very much for the feedback and your suggestions. I appreciate it.

**Comment by acurrieclark** [comment]
Just tagged `v0.10.0` with these changes

**Pull request merged**
